## Primera parte
### Importamos las tablas y revisamos sus datos

In [5]:
# Tuve quye buscar como abrir y manipulkar archivos .xlsx mediante la libreria "openpyxl"
# Al no saber como la denominaban por default, decidi ponerle el acronimo "xl"
import pandas as pd
import openpyxl as xl
DIM_CATEGORY = pd.read_csv("DIM_CATEGORY.csv")
DIM_PRODUCT = pd.read_excel("DIM_PRODUCT.xlsx")
DIM_SEGMENT = pd.read_excel("DIM_SEGMENT.xlsx")
DIM_CALENDAR = pd.read_excel("DIM_CALENDAR.xlsx")
FACT_SALES = pd.read_csv("FACT_SALES.csv")

In [7]:
DIM_CATEGORY

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

In [9]:
# la extension ".info()" nos ayuda a conocer los valores de la tabla así como su tipo de datos
DIM_PRODUCT.info()
DIM_PRODUCT.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [11]:
# La extensión ".head()" nos ayuda a proporcionar las primeras 5 filas de la tabla
# y de esta mamnera no tener tantos datos y poder darnos una idea del contenido   
DIM_SEGMENT.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [13]:
DIM_CALENDAR.head()

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [15]:
FACT_SALES.head()

,SEMANA,CODIGO_ARTÍCULO,VENTAS UNIDADES TOTALES,VALORES VENTAS TOTALES,VENTAS SEMANALES PROMEDIO TOTAL POR UNIDAD,REGION
0,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO
1,30-22,7501042301757,1.526,18.174,30.520,TOTAL AUTOS SCANNING MEXICO
2,30-22,7702626213781,6.671,351.480,4.115,TOTAL AUTOS SCANNING MEXICO
3,30-22,7501058715890,1.231,297.687,2.237,TOTAL AUTOS SCANNING MEXICO
4,30-22,75010587949632,0.016,0.300,3.200,TOTAL AUTOS SCANNING MEXICO

## Segunda parte
### Realizar la limpieza de datos

In [18]:
# DataFrame "DIM_CATEGORY"

# Todas las tablas tienen los nombres de sus columnas bien escritas por lo que los errores tipograficos no existen
# En caso de que si, podemos renombrarlas
# Para este DataFrame en cuestión solo cambiaremos los nombres a español
DIM_CATEGORY.columns = ['# CATEGORIA', 'CATEGORIA']

# No existen valores nulos ya que la tabla es muy pequeña y se puede visualizar a simple vista 

# No existen duplicados ya que se puede ver a simple vista todos los datos de la tabla 

# El unico cambio a realizar en esta tabla sería modificar el nombre de las categorias para pasarlas a español
DIM_CATEGORY['CATEGORIA'] = DIM_CATEGORY['CATEGORIA'].replace('FABRIC TREATMENT AND SANITIZER', 'TRATAMIENTO Y DESINFECTANTE DE TELAS')
# Creo que la segunda categoria no la dectecta por que el  "I" no es igual al valor del DataFrame 
DIM_CATEGORY['CATEGORIA'] = DIM_CATEGORY['CATEGORIA'].replace('AIR CARE', 'CUIDADO DEL AIRE')
DIM_CATEGORY['CATEGORIA'] = DIM_CATEGORY['CATEGORIA'].replace('LAVATORY CARE & BRC', 'CUIDADO DE LAVADORES Y BRC')
DIM_CATEGORY
DIM_CATEGORY.to_csv('DIM_CATEGORY.csv', index=False)

In [20]:
# DataFrame "DIM_PRODUCT"

# Todas las tablas tienen los nombres de sus columnas bien escritas por lo que los errores tipograficos no existen
# En caso de que si, podemos renombrarlas
# Para este DataFrame en cuestión solo cambiaremos los nombres a español
DIM_PRODUCT.columns = ["FABRICANTE", "MARCA", "ARTICULO", "DESCRIPCION_ARTICULO", "CATEGORIA", "PRESENTACION", "ATRIBUTO_1", "ATRIBUTO_2", "ATRIBUTO_3"]

# Verificamos si existen valores nulos con ".isnull().sum()" y de ser así, se rellenaran con "NO VALIDO" 
DIM_PRODUCT.isnull().sum()
DIM_PRODUCT.fillna("NO VALIDO", inplace=True)

# Verificamos si existen datos duplicados
# Eliminar duplicados con la función ".drop_duplicates"
# Al incorporar "inplace=True" aplica los datos directamente en el DataFrame original 
DIM_PRODUCT.drop_duplicates(inplace = True)

# Por ultimo cambiamos los datos dentro del DataFrame de Ingles a Español
DIM_PRODUCT = DIM_PRODUCT.replace({"FABRIC TREATMENT": "TRATAMIENTO DEL TEJIDO", "SAFE BLEACH": "LEJÍA SEGURA",
                                    "GEL": "LÍQUIDO Y GEL", "PRELAVADOR": "PRETRATAMIENTO"})
DIM_PRODUCT
DIM_PRODUCT.to_csv('DIM_PRODUCT.csv', index=False)

In [22]:
# DataFrame "DIM_SEGMENT"

# Todas las tablas tienen los nombres de sus columnas bien escritas por lo que los errores tipograficos no existen
# En caso de que si, podemos renombrarlas
# Para este DataFrame en cuestión solo cambiaremos los nombres a español
DIM_SEGMENT.columns = ["CATEGORIA", "ATRIBUTO_1", "ATRIBUTO_2", "ATRIBUTO_3", "PRESENTACION", "SEGMENTO"]

# Verificamos si existen valores nulos con ".isnull().sum()" y de ser así, se rellenaran con "NO VALIDO" 
DIM_SEGMENT.isnull().sum()
DIM_SEGMENT.fillna("NO VALIDO", inplace=True)

# Verificamos si existen datos duplicados
# Eliminar duplicados con la función ".drop_duplicates"
# Al incorporar "inplace=True" aplica los datos directamente en el DataFrame original 
DIM_SEGMENT.drop_duplicates(inplace = True)

# Por ultimo cambiamos los datos dentro del DataFrame de Ingles a Español
DIM_SEGMENT = DIM_SEGMENT.replace({"BLEACH": "LEJÍA", "FABRIC TREATMENT": "TRATAMIENTO DEL TEJIDO", "SAFE BLEACH": "LEJÍA SEGURA",
                                  "OTHERS": "OTROS", "SANITIZER": "DESINFECTANTE", "LIQUID & GEL": "LÍQUIDO Y GEL", "POWDER": "POLVO", 
                                  "PRETREAT": "PRETRATAMIENTO", "BAR": "BARRA"})
DIM_SEGMENT
DIM_SEGMENT.to_csv('DIM_SEGMENT.csv', index=False)

In [24]:
# DataFrame "DIM_CALENDAR"

# Todas las tablas tienen los nombres de sus columnas bien escritas por lo que los errores tipograficos no existen
# En caso de que si, podemos renombrarlas
# Para este DataFrame en cuestión solo cambiaremos los nombres a español
DIM_CALENDAR.columns = ["SEMANA", "AÑO", "MES", "# SEMANA", "FECHA"]

# Verificamos si existen valores nulos con ".isnull().sum()" y de ser así, se rellenaran con "NO VALIDO" 
DIM_CALENDAR.isnull().sum()
DIM_CALENDAR.fillna("NO VALIDO", inplace=True)

# Verificamos si existen datos duplicados
# Eliminar duplicados con la función ".drop_duplicates"
# Al incorporar "inplace=True" aplica los datos directamente en el DataFrame original 
DIM_CALENDAR.drop_duplicates(inplace = True)

DIM_CALENDAR
DIM_CALENDAR.to_csv('DIM_CALENDAR.csv', index=False)

In [26]:
# DataFrame "FACT_SALES"

# Todas las tablas tienen los nombres de sus columnas bien escritas por lo que los errores tipograficos no existen
# En caso de que si, podemos renombrarlas
# Para este DataFrame en cuestión solo cambiaremos los nombres a español
FACT_SALES.columns = ["SEMANA", "CODIGO_ARTÍCULO", "VENTAS UNIDADES TOTALES", "VALORES VENTAS TOTALES", "VENTAS SEMANALES PROMEDIO TOTAL POR UNIDAD", "REGION"]

# Verificamos si existen valores nulos con ".isnull().sum()" y de ser así, se rellenaran con "NO VALIDO" 
FACT_SALES.isnull().sum()
FACT_SALES.fillna("NO VALIDO", inplace=True)

# Verificamos si existen datos duplicados
# Eliminar duplicados con la función ".drop_duplicates"
# Al incorporar "inplace=True" aplica los datos directamente en el DataFrame original 
FACT_SALES.drop_duplicates(inplace = True)

# Quitamos los puntos y letras existentes en la columna "CODIGO_ARTÍCULO" para convertirlo a entero
#FACT_SALES['CODIGO_ARTÍCULO'] = FACT_SALES['CODIGO_ARTÍCULO'].str.replace('.', '')
#FACT_SALES['CODIGO_ARTÍCULO'] = FACT_SALES['CODIGO_ARTÍCULO'].str.replace('BP', '')


# Convertir las columnas "CODIGO_ARTÍCULO", "VENTAS UNIDADES TOTALES", "VALORES VENTAS TOTALES", "VENTAS SEMANALES PROMEDIO TOTAL POR UNIDAD" a números
FACT_SALES['CODIGO_ARTÍCULO'] = pd.to_numeric(FACT_SALES['CODIGO_ARTÍCULO'])
FACT_SALES['VENTAS UNIDADES TOTALES'] = pd.to_numeric(FACT_SALES['VENTAS UNIDADES TOTALES'])
FACT_SALES['VALORES VENTAS TOTALES'] = pd.to_numeric(FACT_SALES['VALORES VENTAS TOTALES'])
FACT_SALES['VENTAS SEMANALES PROMEDIO TOTAL POR UNIDAD'] = pd.to_numeric(FACT_SALES['VENTAS SEMANALES PROMEDIO TOTAL POR UNIDAD'])

# No comprendi del todo como estaban organizadas las semanas dentro de la columna "week" (ahora "semanas") así que decidi organizar los datos por 
# cada una de las regiuones en cuestión
# Utilizamos el metodo ".sort_values" para organizalos por region y despues modificamos la tabla original con "inplace=True"
FACT_SALES.sort_values(by = 'REGION',ascending=False, inplace=True)

FACT_SALES.head()
FACT_SALES.to_csv('FACT_SALES.csv', index=False)

## Tercera parte 
### Unir los DataFrames relevantes

In [29]:
union1 = pd.merge(
    DIM_PRODUCT,
    DIM_SEGMENT,
    on=['PRESENTACION', "CATEGORIA", "ATRIBUTO_2"],
    how="outer",
    suffixes=('x', 'y')
)

# Paso 2: Complementar los valores "NO DEFINIDO" para ATRIBUTO_1 y ATRIBUTO_3
union1['ATRIBUTO_1'] = union1['ATRIBUTO_1x'].where(union1['ATRIBUTO_1x'] != 'NO DEFINIDO', union1['ATRIBUTO_1y'])
union1['ATRIBUTO_3'] = union1['ATRIBUTO_3x'].where(union1['ATRIBUTO_3x'] != 'NO DEFINIDO', union1['ATRIBUTO_3y'])

# Paso 3: Eliminar columnas auxiliares
resultado = union1.drop(columns=['ATRIBUTO_1x', 'ATRIBUTO_1y', 'ATRIBUTO_3x', 'ATRIBUTO_3y'])

# Mostrar resultado
resultado


# Verifica las claves únicas en ambas tablas
claves_product = DIM_PRODUCT[['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2']].drop_duplicates()
claves_segment = DIM_SEGMENT[['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2']].drop_duplicates()

# Encuentra coincidencias
coincidencias = pd.merge(
    claves_product, 
    claves_segment, 
    on=['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2'], 
    how='inner'
)

print("Total claves únicas en DIM_PRODUCT:", len(claves_product))
print("Total claves únicas en DIM_SEGMENT:", len(claves_segment))
print("Total coincidencias entre tablas:", len(coincidencias))


print(DIM_PRODUCT[['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2']].info())
print(DIM_SEGMENT[['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2']].info())


union1 = pd.merge(
    DIM_PRODUCT,
    DIM_SEGMENT,
    on=['PRESENTACION', 'CATEGORIA', 'ATRIBUTO_2'],
    how='outer',
    suffixes=('x', 'y'),
    indicator=True
)

print(union1['_merge'].value_counts())
# Guardar el DataFrame resultado en un archivo .csv
resultado.to_csv('resultado.csv', index=False)

Total claves únicas en DIM_PRODUCT: 9
Total claves únicas en DIM_SEGMENT: 13
Total coincidencias entre tablas: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PRESENTACION  505 non-null    object
 1   CATEGORIA     505 non-null    int64
 2   ATRIBUTO_2    505 non-null    object
dtypes: int64(1), object(2)
memory usage: 12.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PRESENTACION  53 non-null     object
 1   CATEGORIA     53 non-null     int64
 2   ATRIBUTO_2    53 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.4+ KB
None
_merge
both          4017
left_only       72
right_only      14
Name: count, dtype: int64

## Quinta parte 
### Guardar el conjunto de datos consolidado