# Importación de datos para DIM_CALENDAR

In [54]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

# Configuración de conexión
server = 'DESKTOP-2U14VQ3' 
database = 'Proyecto_empresa_aliada'
params = urllib.parse.quote_plus(f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;')
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# Cargar el Excel
df = pd.read_excel('DIM_CALENDAR.xlsx')

# Visualizar los primeros 5 registros 
df.head()

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

In [56]:
# Convertimos a string y quitamos espacios extra
df['WEEK'] = df['WEEK'].astype(str).str.strip()

In [58]:
# Hacemos un submit para cargar los datos
try:
    df.to_sql('DIM_CALENDAR', con=engine, if_exists='append', index=False)
    print("Importación exitosa")
except Exception as e:
    print(f"Error: {e}")

Importación exitosa

# Importación de datos para DIM_PRODUCT

In [61]:
# Configuración de conexión
server = 'DESKTOP-2U14VQ3' 
database = 'Proyecto_empresa_aliada'
params = urllib.parse.quote_plus(f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;')
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# Cargar el Excel
df = pd.read_excel('DIM_PRODUCT.xlsx')

# Visualizar los primeros 5 registros 
df.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

In [63]:
# Convertimos a string y quitamos espacios extra
df['ITEM'] = df['ITEM'].astype(str).str.strip()

In [65]:
# Hacemos un submit para cargar los datos
try:
    df.to_sql('DIM_PRODUCT', con=engine, if_exists='replace', index=False)
    print("Importación exitosa")
except Exception as e:
    print(f"Error: {e}")

Importación exitosa

# Importación de datos para DIM_SEGMENT

In [68]:
# Configuración de conexión
server = 'DESKTOP-2U14VQ3' 
database = 'Proyecto_empresa_aliada'
params = urllib.parse.quote_plus(f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;')
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# Cargar el Excel
df = pd.read_excel('DIM_SEGMENT.xlsx')

# Visualizar los primeros 5 registros 
df.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [70]:
# Hacemos un submit para cargar los datos
try:
    df.to_sql('DIM_SEGMENT', con=engine, if_exists='append', index=False)
    print("Importación exitosa")
except Exception as e:
    print(f"Error: {e}")

Importación exitosa